// All page copy lives here so the language toggle can swap the whole site.
// EN is the canonical copy taken from the SalesEcho landing page; ES is a
// faithful translation so the "English / Español" switch actually does something.

export const LANGS = [
  { code: 'en', label: 'English' },
  { code: 'es', label: 'Español' },
]

export const content = {
  en: {
    nav: { signIn: 'Sign In' },
    hero: {
      title: ['Practice.', 'Sell Live.', 'Close more deals.'],
      rocket: '🚀',
      sub: ['Your real-time AI sales call assistant: coaches you ', 'before', ', ', 'during', ', and ', 'after', ' every call.'],
      primary: 'Close More Deals',
      primaryEmoji: '🎯',
      secondary: 'Enterprise',
      secondaryEmoji: '🏢',
      trial: '3-day trial for $1',
      worksWith: 'Works with',
      more: '+ More',
      seeHow: 'See how it works',
    },
    demo: {
      videoTab: 'Video Demo',
      interactiveTab: 'Interactive Demo',
      videoTitle: 'Watch a 90-second tour',
      videoSub: 'See how SalesEcho rides along on a real call and feeds you the right line at the right moment.',
      playLabel: 'Play overview',
      tryLabel: 'Try the live demo below 👇',
      callTitle: 'Live discovery call',
      you: 'You (Rep)',
      prospect: 'Jordan — VP Sales, Northwind',
      start: 'Start call',
      restart: 'Restart',
      pause: 'Pause',
      resume: 'Resume',
      ended: 'Call ended',
      coachingTitle: 'AI Coaching',
      phaseBefore: 'Before',
      phaseDuring: 'During',
      phaseAfter: 'After',
    },
    features: {
      heading: 'One assistant for the whole deal',
      sub: 'SalesEcho is with you at every stage — not just a notetaker.',
      items: [
        { icon: '🧠', title: 'Pre-call prep', body: 'Walk in ready. Get a research brief on the account, the buyer, and the likely objections before you dial.' },
        { icon: '⚡', title: 'Live coaching', body: 'Real-time cues whisper the next question, the perfect rebuttal, and when to stop talking — right on your screen.' },
        { icon: '📊', title: 'Talk-track analytics', body: 'Talk/listen ratio, sentiment, and objection tracking scored automatically on every call.' },
        { icon: '📝', title: 'Auto follow-up', body: 'A summary, action items, and a draft follow-up email in your inbox before the call even ends.' },
        { icon: '🎯', title: 'Battle cards', body: 'Competitor mentioned? The right positioning surfaces instantly so you never freeze.' },
        { icon: '🔌', title: 'Works everywhere', body: 'Drops into Google Meet, Zoom, and Microsoft Teams. No new habits to learn.' },
      ],
    },
    how: {
      heading: 'How it works',
      steps: [
        { n: '01', title: 'Connect your calendar', body: 'SalesEcho joins your sales calls automatically across Meet, Zoom, and Teams.' },
        { n: '02', title: 'Get coached live', body: 'As the conversation unfolds, AI suggestions appear in a private side panel only you can see.' },
        { n: '03', title: 'Close & follow up', body: 'Get an instant recap, CRM-ready notes, and a follow-up draft the moment you hang up.' },
      ],
    },
    pricing: {
      heading: 'Simple pricing',
      sub: 'Start with a 3-day trial for $1. Cancel anytime.',
      monthly: 'Monthly',
      yearly: 'Yearly',
      yearlyNote: 'Save 20%',
      plans: [
        { name: 'Starter', price: { monthly: 29, yearly: 23 }, tagline: 'For individual reps getting started.', cta: 'Start $1 trial', featured: false,
          features: ['Live call coaching', 'Up to 20 calls / mo', 'Auto summaries & follow-ups', 'Meet, Zoom & Teams'] },
        { name: 'Pro', price: { monthly: 59, yearly: 47 }, tagline: 'For closers who live on the phone.', cta: 'Start $1 trial', featured: true,
          features: ['Everything in Starter', 'Unlimited calls', 'Battle cards & objection AI', 'CRM sync (HubSpot, Salesforce)', 'Talk-track analytics'] },
        { name: 'Enterprise', price: { monthly: null, yearly: null }, tagline: 'For teams that need control & scale.', cta: 'Talk to sales', featured: false,
          features: ['Everything in Pro', 'Team analytics & coaching', 'SSO / SAML & SCIM', 'Custom playbooks', 'Dedicated success manager'] },
      ],
      contact: 'Custom',
      perMonth: '/mo',
    },
    testimonials: {
      heading: 'Reps close more with SalesEcho',
      items: [
        { quote: 'I booked 30% more second meetings in my first month. The live objection prompts are unreal.', name: 'Maya R.', role: 'AE, SaaS startup' },
        { quote: 'It’s like having my sales manager on every call — without the awkwardness.', name: 'Devin K.', role: 'SDR, fintech' },
        { quote: 'The post-call summaries alone save me an hour a day. Closing rate is up too.', name: 'Priya S.', role: 'Account Executive' },
      ],
    },
    faq: {
      heading: 'Frequently asked questions',
      items: [
        { q: 'Can the other people on the call see the coaching?', a: 'No. The coaching panel is private and only visible to you. The prospect sees a normal call.' },
        { q: 'Which platforms are supported?', a: 'Google Meet, Zoom, and Microsoft Teams today, with more on the way.' },
        { q: 'How does the $1 trial work?', a: 'You get full access for 3 days for $1. Cancel anytime before it ends and you won’t be charged again.' },
        { q: 'Is my call data secure?', a: 'Calls are encrypted in transit and at rest. You control retention and can delete recordings anytime.' },
        { q: 'Do you integrate with my CRM?', a: 'Yes — Pro and Enterprise sync notes and action items to HubSpot and Salesforce automatically.' },
      ],
    },
    cta: {
      heading: 'Ready to close more deals?',
      sub: 'Join thousands of reps who never walk into a call unprepared.',
      button: 'Close More Deals',
    },
    footer: {
      tagline: 'Your real-time AI sales call assistant.',
      cols: [
        { title: 'Product', links: ['Features', 'Pricing', 'Integrations', 'Changelog'] },
        { title: 'Company', links: ['About', 'Careers', 'Blog', 'Contact'] },
        { title: 'Legal', links: ['Privacy', 'Terms', 'Security', 'DPA'] },
      ],
      rights: 'All rights reserved.',
      disclaimer: 'Unofficial demo clone built for educational purposes. Not affiliated with SalesEcho.',
    },
    signin: {
      title: 'Welcome back',
      sub: 'Sign in to your SalesEcho account.',
      email: 'Email',
      password: 'Password',
      button: 'Sign In',
      google: 'Continue with Google',
      noAccount: 'No account?',
      signup: 'Start your $1 trial',
      demoNote: 'Demo only — no real authentication.',
    },
  },

  es: {
    nav: { signIn: 'Iniciar sesión' },
    hero: {
      title: ['Practica.', 'Vende en vivo.', 'Cierra más tratos.'],
      rocket: '🚀',
      sub: ['Tu asistente de llamadas de ventas con IA en tiempo real: te guía ', 'antes', ', ', 'durante', ' y ', 'después', ' de cada llamada.'],
      primary: 'Cierra más tratos',
      primaryEmoji: '🎯',
      secondary: 'Empresas',
      secondaryEmoji: '🏢',
      trial: 'Prueba de 3 días por $1',
      worksWith: 'Funciona con',
      more: '+ Más',
      seeHow: 'Mira cómo funciona',
    },
    demo: {
      videoTab: 'Video demo',
      interactiveTab: 'Demo interactiva',
      videoTitle: 'Mira un recorrido de 90 segundos',
      videoSub: 'Descubre cómo SalesEcho te acompaña en una llamada real y te da la frase correcta en el momento justo.',
      playLabel: 'Reproducir resumen',
      tryLabel: 'Prueba la demo en vivo abajo 👇',
      callTitle: 'Llamada de descubrimiento en vivo',
      you: 'Tú (Vendedor)',
      prospect: 'Jordan — VP de Ventas, Northwind',
      start: 'Iniciar llamada',
      restart: 'Reiniciar',
      pause: 'Pausar',
      resume: 'Reanudar',
      ended: 'Llamada finalizada',
      coachingTitle: 'Coaching con IA',
      phaseBefore: 'Antes',
      phaseDuring: 'Durante',
      phaseAfter: 'Después',
    },
    features: {
      heading: 'Un asistente para todo el trato',
      sub: 'SalesEcho te acompaña en cada etapa — no es solo un tomador de notas.',
      items: [
        { icon: '🧠', title: 'Preparación previa', body: 'Llega listo. Recibe un informe de la cuenta, el comprador y las objeciones probables antes de llamar.' },
        { icon: '⚡', title: 'Coaching en vivo', body: 'Señales en tiempo real te susurran la siguiente pregunta, la réplica perfecta y cuándo callar — en tu pantalla.' },
        { icon: '📊', title: 'Analítica de conversación', body: 'Ratio de habla/escucha, sentimiento y seguimiento de objeciones puntuados automáticamente.' },
        { icon: '📝', title: 'Seguimiento automático', body: 'Un resumen, tareas y un borrador de correo en tu bandeja antes de colgar.' },
        { icon: '🎯', title: 'Battle cards', body: '¿Mencionan a un competidor? El posicionamiento correcto aparece al instante.' },
        { icon: '🔌', title: 'Funciona en todas partes', body: 'Se integra con Google Meet, Zoom y Microsoft Teams. Sin nuevos hábitos.' },
      ],
    },
    how: {
      heading: 'Cómo funciona',
      steps: [
        { n: '01', title: 'Conecta tu calendario', body: 'SalesEcho se une a tus llamadas automáticamente en Meet, Zoom y Teams.' },
        { n: '02', title: 'Recibe coaching en vivo', body: 'Mientras hablas, las sugerencias de IA aparecen en un panel privado que solo tú ves.' },
        { n: '03', title: 'Cierra y haz seguimiento', body: 'Recibe un resumen instantáneo, notas para el CRM y un borrador de correo al colgar.' },
      ],
    },
    pricing: {
      heading: 'Precios simples',
      sub: 'Empieza con una prueba de 3 días por $1. Cancela cuando quieras.',
      monthly: 'Mensual',
      yearly: 'Anual',
      yearlyNote: 'Ahorra 20%',
      plans: [
        { name: 'Starter', price: { monthly: 29, yearly: 23 }, tagline: 'Para vendedores que empiezan.', cta: 'Prueba por $1', featured: false,
          features: ['Coaching en vivo', 'Hasta 20 llamadas / mes', 'Resúmenes y seguimientos', 'Meet, Zoom y Teams'] },
        { name: 'Pro', price: { monthly: 59, yearly: 47 }, tagline: 'Para cerradores que viven del teléfono.', cta: 'Prueba por $1', featured: true,
          features: ['Todo lo de Starter', 'Llamadas ilimitadas', 'Battle cards y IA de objeciones', 'Sync con CRM (HubSpot, Salesforce)', 'Analítica de conversación'] },
        { name: 'Enterprise', price: { monthly: null, yearly: null }, tagline: 'Para equipos que necesitan control y escala.', cta: 'Hablar con ventas', featured: false,
          features: ['Todo lo de Pro', 'Analítica de equipo', 'SSO / SAML y SCIM', 'Playbooks personalizados', 'Gerente de éxito dedicado'] },
      ],
      contact: 'A medida',
      perMonth: '/mes',
    },
    testimonials: {
      heading: 'Los vendedores cierran más con SalesEcho',
      items: [
        { quote: 'Reservé un 30% más de segundas reuniones en mi primer mes. Los avisos de objeciones en vivo son increíbles.', name: 'Maya R.', role: 'AE, startup SaaS' },
        { quote: 'Es como tener a mi gerente de ventas en cada llamada — sin la incomodidad.', name: 'Devin K.', role: 'SDR, fintech' },
        { quote: 'Solo los resúmenes posteriores me ahorran una hora al día. Y cierro más.', name: 'Priya S.', role: 'Ejecutiva de cuentas' },
      ],
    },
    faq: {
      heading: 'Preguntas frecuentes',
      items: [
        { q: '¿Las demás personas en la llamada ven el coaching?', a: 'No. El panel de coaching es privado y solo tú lo ves. El prospecto ve una llamada normal.' },
        { q: '¿Qué plataformas son compatibles?', a: 'Google Meet, Zoom y Microsoft Teams hoy, con más en camino.' },
        { q: '¿Cómo funciona la prueba de $1?', a: 'Tienes acceso completo por 3 días por $1. Cancela antes de que termine y no se te cobrará de nuevo.' },
        { q: '¿Mis datos de llamadas están seguros?', a: 'Las llamadas se cifran en tránsito y en reposo. Tú controlas la retención y puedes borrar grabaciones cuando quieras.' },
        { q: '¿Se integra con mi CRM?', a: 'Sí — Pro y Enterprise sincronizan notas y tareas con HubSpot y Salesforce automáticamente.' },
      ],
    },
    cta: {
      heading: '¿Listo para cerrar más tratos?',
      sub: 'Únete a miles de vendedores que nunca llegan sin preparación a una llamada.',
      button: 'Cierra más tratos',
    },
    footer: {
      tagline: 'Tu asistente de llamadas de ventas con IA en tiempo real.',
      cols: [
        { title: 'Producto', links: ['Funciones', 'Precios', 'Integraciones', 'Novedades'] },
        { title: 'Empresa', links: ['Acerca de', 'Empleo', 'Blog', 'Contacto'] },
        { title: 'Legal', links: ['Privacidad', 'Términos', 'Seguridad', 'DPA'] },
      ],
      rights: 'Todos los derechos reservados.',
      disclaimer: 'Clon de demostración no oficial con fines educativos. No afiliado con SalesEcho.',
    },
    signin: {
      title: 'Bienvenido de nuevo',
      sub: 'Inicia sesión en tu cuenta de SalesEcho.',
      email: 'Correo',
      password: 'Contraseña',
      button: 'Iniciar sesión',
      google: 'Continuar con Google',
      noAccount: '¿Sin cuenta?',
      signup: 'Empieza tu prueba de $1',
      demoNote: 'Solo demo — sin autenticación real.',
    },
  },
}

// The scripted live call used by the Interactive Demo. Each line is timed (ms
// from call start) and may attach an AI coaching card shown in the side panel.
export const callScript = {
  en: {
    prep: {
      phase: 'Before',
      title: 'Pre-call brief ready',
      lines: [
        'Northwind — 220 employees, scaling outbound team.',
        'Jordan was promoted to VP 6 weeks ago — wants quick wins.',
        'Likely objection: "We already use a competitor."',
        'Goal: book a 30-min technical follow-up.',
      ],
    },
    transcript: [
      { t: 1200, who: 'prospect', text: 'Hey, thanks for hopping on. I’ve got about 15 minutes.' },
      { t: 3200, who: 'you', text: 'Appreciate it, Jordan. Congrats on the VP role — how’s the new team shaping up?' },
      { t: 3300, who: 'coach', phase: 'During', kind: 'good', title: 'Nice — opened with their win', text: 'Personalizing on the promotion builds rapport fast. Keep it short and pivot to discovery.' },
      { t: 6200, who: 'prospect', text: 'Busy! We’re trying to ramp outbound but reps are inconsistent on calls.' },
      { t: 7000, who: 'coach', phase: 'During', kind: 'tip', title: 'Ask the impact question', text: 'Quantify the pain: "What’s an inconsistent call costing you per quarter in pipeline?"' },
      { t: 10200, who: 'you', text: 'Got it. What’s that inconsistency costing you in pipeline each quarter?' },
      { t: 13200, who: 'prospect', text: 'Honestly a lot. But we already pay for Gong, so I’m not looking for another tool.' },
      { t: 13600, who: 'coach', phase: 'During', kind: 'objection', title: 'Objection: "We already use Gong"', text: 'Don’t fight it. Position alongside: Gong reviews calls after; SalesEcho coaches live, during the call. Ask: "Does Gong help reps in the moment, or after?"' },
      { t: 17800, who: 'you', text: 'Totally — Gong’s great for reviewing calls after. SalesEcho is different: it coaches reps live, in the moment. Does anything help them during the call today?' },
      { t: 21200, who: 'prospect', text: 'No… that’s actually the gap. Live would be interesting.' },
      { t: 22000, who: 'coach', phase: 'During', kind: 'good', title: 'Buying signal 🎯', text: 'They said "interesting." Trial-close now: propose the technical follow-up while interest is high.' },
      { t: 25200, who: 'you', text: 'Great — let’s get your two top reps on a 30-minute live walkthrough this week. Does Thursday work?' },
      { t: 28400, who: 'prospect', text: 'Thursday afternoon works. Send the invite.' },
      { t: 29200, who: 'coach', phase: 'During', kind: 'good', title: 'Meeting booked ✅', text: 'Confirmed next step. Stop selling — recap and end on time to respect their 15 minutes.' },
    ],
    summary: {
      phase: 'After',
      title: 'Call summary & next steps',
      lines: [
        '✅ Outcome: 30-min technical walkthrough booked (Thu PM).',
        '🎯 Pain: inconsistent rep performance on live calls.',
        '🧩 Objection handled: "already use Gong" → positioned as live vs. retrospective.',
        '📤 Follow-up email drafted with calendar invite + 1-pager.',
        '📈 Talk/listen ratio: 42% / 58% — healthy.',
      ],
    },
  },
  es: {
    prep: {
      phase: 'Antes',
      title: 'Informe previo listo',
      lines: [
        'Northwind — 220 empleados, escalando equipo de outbound.',
        'Jordan fue ascendido a VP hace 6 semanas — busca victorias rápidas.',
        'Objeción probable: "Ya usamos a un competidor".',
        'Objetivo: agendar un seguimiento técnico de 30 min.',
      ],
    },
    transcript: [
      { t: 1200, who: 'prospect', text: 'Hola, gracias por conectarte. Tengo unos 15 minutos.' },
      { t: 3200, who: 'you', text: 'Gracias a ti, Jordan. Felicidades por el rol de VP — ¿cómo va el nuevo equipo?' },
      { t: 3300, who: 'coach', phase: 'Durante', kind: 'good', title: 'Bien — abriste con su logro', text: 'Personalizar sobre el ascenso crea rapport rápido. Sé breve y pasa al descubrimiento.' },
      { t: 6200, who: 'prospect', text: '¡Ocupado! Intentamos escalar outbound pero los vendedores son inconsistentes en las llamadas.' },
      { t: 7000, who: 'coach', phase: 'Durante', kind: 'tip', title: 'Haz la pregunta de impacto', text: 'Cuantifica el dolor: "¿Cuánto te cuesta por trimestre en pipeline una llamada inconsistente?"' },
      { t: 10200, who: 'you', text: 'Entiendo. ¿Cuánto les cuesta esa inconsistencia en pipeline cada trimestre?' },
      { t: 13200, who: 'prospect', text: 'La verdad, mucho. Pero ya pagamos Gong, así que no busco otra herramienta.' },
      { t: 13600, who: 'coach', phase: 'Durante', kind: 'objection', title: 'Objeción: "Ya usamos Gong"', text: 'No la combatas. Posiciónate al lado: Gong revisa llamadas después; SalesEcho guía en vivo, durante la llamada. Pregunta: "¿Gong ayuda en el momento o después?"' },
      { t: 17800, who: 'you', text: 'Claro — Gong es genial para revisar después. SalesEcho es distinto: guía a los vendedores en vivo. ¿Algo les ayuda hoy durante la llamada?' },
      { t: 21200, who: 'prospect', text: 'No… ese es justo el hueco. En vivo sería interesante.' },
      { t: 22000, who: 'coach', phase: 'Durante', kind: 'good', title: 'Señal de compra 🎯', text: 'Dijo "interesante". Haz un cierre de prueba: propón el seguimiento técnico ahora.' },
      { t: 25200, who: 'you', text: 'Perfecto — pongamos a tus dos mejores vendedores en una demo en vivo de 30 min esta semana. ¿El jueves?' },
      { t: 28400, who: 'prospect', text: 'El jueves por la tarde funciona. Envía la invitación.' },
      { t: 29200, who: 'coach', phase: 'Durante', kind: 'good', title: 'Reunión agendada ✅', text: 'Siguiente paso confirmado. Deja de vender — resume y termina a tiempo para respetar sus 15 minutos.' },
    ],
    summary: {
      phase: 'Después',
      title: 'Resumen y próximos pasos',
      lines: [
        '✅ Resultado: demo técnica de 30 min agendada (jue PM).',
        '🎯 Dolor: rendimiento inconsistente en llamadas en vivo.',
        '🧩 Objeción resuelta: "ya usan Gong" → posicionado en vivo vs. retrospectivo.',
        '📤 Correo de seguimiento redactado con invitación + 1-pager.',
        '📈 Ratio habla/escucha: 42% / 58% — saludable.',
      ],
    },
  },
}
